openapi: 3.0.0
info:
  title: Spring Boot Exercise API
  version: 1.0.0
paths:
  /api/login:
    post:
      summary: Logs in a user
      operationId: login
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                description: Session token
  /api/logout:
    post:
      summary: Logs out the user
      operationId: logout
      tags:
        - auth
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful logout
        '401':
          description: Unauthorized, invalid session token

  /address/get:
    get:
      summary: Get address by ID
      operationId: getAddress
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Address object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
        '404':
          description: Address not found

  /address/create:
    post:
      summary: Create a new address
      operationId: createAddress
      requestBody:
        description: Address to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
        '400':
          description: Invalid input

components:
  schemas:
    Address:
      type: object
      properties:
        id:
          type: string
        street:
          type: string
        city:
          type: string
        postalCode:
          type: string
